![logo](img/itq.png)

## 0.2 Estandarizacion

![logo](img/python_logo.png)

*Anderson Soto*


# Estandarización de Datos con StandardScaler

En este ejemplo aplicaremos estandarización a un conjunto de datos usando `StandardScaler` de `sklearn.preprocessing`.

In [1]:
from sklearn import preprocessing
import numpy as np

## Carga de datos

Creamos el conjunto de datos de entrenamiento `X_train`.

In [6]:
# Carga de datos
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

## Limpieza de datos: Estandarización

Utilizamos `StandardScaler` para centrar los datos en media 0 y desviación estándar 1.

In [7]:
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std = standardizer.fit_transform(X_train)

print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


## Copia del conjunto de datos

Creamos una segunda matriz para comprobar que `fit()` y `transform()` por separado producen el mismo resultado.

In [8]:
X_train_2 = np.array([[ 1., -1.,  2.],
                      [ 2.,  0.,  0.],
                      [ 0.,  1., -1.]])

## Aplicación separada de `fit()` y `transform()`

Primero ajustamos el modelo con `fit()` y luego transformamos los datos con `transform()`.

In [9]:
f = preprocessing.StandardScaler()
f = f.fit(X_train)

X_train_2_std = f.transform(X_train_2)

print(X_train_2_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


## Verificación de resultados

Comprobamos si ambas matrices estandarizadas son iguales.

In [10]:
print(np.array_equiv(X_train_std, X_train_2_std))

True


## Github

https://github.com/Joji-free/machine2026.git