![logo](img/itq.png)

## 0.1 Normalizacion

![logo](img/python_logo.png)

*Anderson Soto*

# Normalización de Datos con MinMaxScaler

En este ejemplo trabajaremos con un conjunto de datos numéricos y aplicaremos una normalización usando `MinMaxScaler` de `sklearn.preprocessing`.


In [1]:
from sklearn import preprocessing
import numpy as np

## Carga de datos

Creamos un conjunto de datos de entrenamiento llamado `X_train`.

In [4]:
# Carga de datos
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


## Limpieza de datos: Normalización

Utilizamos `MinMaxScaler` para escalar los valores entre 0 y 1.

In [5]:
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train)

## Resultados de la normalización
Mostramos el conjunto de datos normalizado.

In [6]:
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


## Verificación usando `fit` y `transform` por separado

Comprobamos que aplicar `fit()` y luego `transform()` produce el mismo resultado que `fit_transform()`.

In [7]:
X_train_2 = np.copy(X_train)

# Ajustar el modelo
f = normalizer.fit(X_train)

# Transformar los datos
X_train_norm_2 = f.transform(X_train)

# Comparar resultados
print(np.array_equiv(X_train_norm, X_train_norm_2))

True


## Normalización de datos de prueba

Para los datos de test SOLO se debe usar `transform()`, 
NO se debe volver a usar `fit()`.

In [8]:
X_test = np.array([[ 1., -3.,  2.],
                   [ 3.,  0.,  0.],
                   [ 0.,  4., -1.]])

# Aplicar únicamente transform
X_test_norm = normalizer.transform(X_test)

print(X_test_norm)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


## Github

https://github.com/Joji-free/machine2026.git